version: '3.8'

services:
  web:
    image: dennisrosario/king-it-test-hotel-offers-web:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}

    restart: unless-stopped
